In [13]:
import numpy as np

In [ ]:
# TASK - 1

In [2]:
a1 = np.arange(1,11)
print(a1)

[ 1  2  3  4  5  6  7  8  9 10]


In [10]:
print(a1.shape , a1.size , a1.ndim)

(10,) 10 1


In [4]:
a2 = np.arange(1,10).reshape(3,3)
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
print(a2.shape , a2.size , a2.ndim)

(3, 3) 9 2


In [5]:
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
a3 = np.random.rand(3,5,3)

In [7]:
a3


array([[[0.49258403, 0.11665126, 0.1860171 ],
        [0.65084793, 0.47015495, 0.02876611],
        [0.67133618, 0.10289254, 0.31979791],
        [0.77787615, 0.36808942, 0.53310628],
        [0.19377739, 0.16155087, 0.48512797]],

       [[0.74017088, 0.13883849, 0.33105121],
        [0.23969051, 0.48762994, 0.42453853],
        [0.09734644, 0.26408729, 0.59673012],
        [0.87111451, 0.71037529, 0.68321166],
        [0.51213994, 0.86421748, 0.34485938]],

       [[0.48170024, 0.0372974 , 0.15868942],
        [0.72695092, 0.07477535, 0.14446671],
        [0.56828692, 0.51658653, 0.06910582],
        [0.11298429, 0.57231767, 0.43256019],
        [0.72576915, 0.24079303, 0.2199064 ]]])

In [12]:
print(a3.shape , a3.size , a3.ndim)

(3, 5, 3) 45 3


In [14]:
# TASK - 2


In [18]:
data = [10, 20, 30, 40, 50, 60, 70, 80, 90]
arr = np.array(data)
# print(arr)

In [17]:
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [19]:
first3 = arr[:3]
first3

array([10, 20, 30])

In [21]:
alt = arr[: :2]
alt

array([10, 30, 50, 70, 90])

In [24]:
rev = arr[: : -1]
rev

array([90, 80, 70, 60, 50, 40, 30, 20, 10])

In [25]:
# TASK - 3

In [26]:
A = np.random.randint(1, 21, size=5)
B = np.random.randint(1, 21, size=5)

In [30]:
print(A)
print(B)

[15  1  7  3  5]
[ 3 11 18 14 19]


In [31]:
print('Addition : ',A+B)

Addition :  [18 12 25 17 24]


In [32]:
print('Subtraction : ',A-B)
print('Multiply : ',A*B)
print('Divide :',A/B)

Subtraction :  [ 12 -10 -11 -11 -14]
Multiply :  [ 45  11 126  42  95]
Divide : [5.         0.09090909 0.38888889 0.21428571 0.26315789]


In [36]:
dot = np.dot(A,B)
print("Dot Product = ",dot)

Dot Product =  319


In [37]:
print("Mean:", np.mean(A))
print("Median:", np.median(A))
print("Standard Deviation:", np.std(A))
print("Variance:", np.var(A))

Mean: 6.2
Median: 5.0
Standard Deviation: 4.833218389437829
Variance: 23.360000000000003


In [38]:
max_val = np.max(B)
min_val = np.min(B)
max_idx = np.argmax(B)
min_idx = np.argmin(B)

In [40]:
print("Maximum Value:", max_val, "| Index:", max_idx)
print("Minimum Value:", min_val, "| Index:", min_idx)

Maximum Value: 19 | Index: 4
Minimum Value: 3 | Index: 0


In [41]:
# TASK - 4

In [42]:
array = np.arange(1,13)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [44]:
array_2d = array.reshape(4, 3)
array_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [45]:
array_3d = array.reshape(2, 2, 3)
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [49]:
transposed_2d = array_2d.T
print("Transpose of 2d array : ",transposed_2d)
print("Shape", transposed_2d.shape)

Transpose of 2d array :  [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
Shape (3, 4)


In [50]:
# TASK - 5

In [53]:
array = np.random.randint(10, 51, size=15)
array

array([16, 28, 28, 23, 44, 33, 40, 40, 35, 25, 22, 49, 29, 21, 10],
      dtype=int32)

In [55]:
gt = array[array >25]
print("Greater then 25 :",gt)

Greater then 25 : [28 28 44 33 40 40 35 49 29]


In [57]:
mod = np.where(array<30,0,array)
print("Modified array",mod)

Modified array [ 0  0  0  0 44 33 40 40 35  0  0 49  0  0  0]


In [60]:
div = np.sum(array%5==0)
print("Number of elements divisible by 5:",div)

Number of elements divisible by 5: 5


In [61]:
# TASK - 6

In [62]:
eq_spaced = np.linspace(0, 1, 10)
print("10 equally spaced values between 0 and 1 :", eq_spaced)

10 equally spaced values between 0 and 1 : [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [64]:
id_matrix = np.eye(4)
print("Identity matrix (4x4) :", id_matrix)

Identity matrix (4x4) : [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [65]:
ran_array = np.random.randint(1, 101, size=20)
print("Original Random Array :", ran_array)

Original Random Array : [39 37 29 29 27 46 20 55 30 60 29 85 18 46 46 27 75 89 40 66]


In [70]:
sorted = np.sort(ran_array)
five_large = sorted[-5:]
print("5 Largest Elements:", five_large)

5 Largest Elements: [60 66 75 85 89]


In [71]:
# TASK - 7

In [77]:
import time

In [78]:
A = np.random.rand(100, 100)
B = np.random.rand(100, 100)


In [80]:
start_time = time.time()
C = np.dot(A, B)
mult_time = time.time() - start_time
print("Matrix multiplication completed in {:.4f} seconds.".format(mult_time))
print(C)

Matrix multiplication completed in 0.0006 seconds.
[[22.73594806 25.58799348 26.01668752 ... 24.45266501 25.478522
  24.43117576]
 [21.39294131 24.43598041 26.23093013 ... 26.55499685 24.28888041
  23.73561186]
 [22.46633313 26.54827413 26.49259151 ... 26.21940125 26.647047
  25.61675966]
 ...
 [22.22398251 28.68303197 28.55155233 ... 28.89329997 31.22542423
  28.60346268]
 [23.67414543 27.60605213 28.4675726  ... 28.69818083 28.58250133
  26.25895178]
 [21.73139544 26.67739771 25.76726205 ... 24.47122655 27.56711621
  24.6683093 ]]


In [81]:
start_time = time.time()
det_C = np.linalg.det(C)
det_time = time.time() - start_time
print('Time Taken : ',det_time)
print("Determinant ; ",det_C) 

Time Taken :  0.00030422210693359375
Determinant ;  -5.229256141824326e+49


In [85]:
if np.isclose(det_C, 0):
    print("Matrix is singular and cannot be inverted.")
else:
    start_time = time.time()
    inverse_C = np.linalg.inv(C)
    inv_time = time.time() - start_time
    print("Inverse computed in {:.4f} seconds.".format(inv_time))
    print(inverse_C)

Inverse computed in 0.0311 seconds.
[[  0.7580443    0.62140783   0.09241088 ...  -0.29267434   0.20016089
   -0.14789495]
 [ -3.78268206  -1.1976529    1.20811541 ...  -1.99343351  -5.26254532
    3.95447261]
 [ -8.21175     -0.54282206   2.88735856 ...  -4.74321675  -9.68391421
    6.65006714]
 ...
 [ -0.88307019  -0.66851917   0.93080328 ...  -1.31272889  -1.56695514
    1.04263785]
 [ -8.46674727  -1.63369592   3.14063132 ...  -5.59891323 -10.10789118
    6.61989074]
 [ -6.52823336  -0.60011085   2.76966888 ...  -4.2670965   -8.15299271
    6.00208111]]
